config/routes.rb
RailsinstallerDemo::Application.routes.draw do
  resources :tickers

  resources :games

  resources :spielers

  resources :teams

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/spieler.rb
class Spieler < ActiveRecord::Base
	belongs_to :team
end

app/controllers/spielers_controller.rb
class SpielersController < ApplicationController
  # GET /spielers
  # GET /spielers.json
  def index
    @spielers = Spieler.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spielers }
    end
  end

  # GET /spielers/1
  # GET /spielers/1.json
  def show
    @spieler = Spieler.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spieler }
    end
  end

  # GET /spielers/new
  # GET /spielers/new.json
  def new
    @spieler = Spieler.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spieler }
    end
  end

  # GET /spielers/1/edit
  def edit
    @spieler = Spieler.find(params[:id])
  end

  # POST /spielers
  # POST /spielers.json
  def create
    @spieler = Spieler.new(params[:spieler])

    respond_to do |format|
      if @spieler.save
        format.html { redirect_to @spieler, notice: 'Spieler was successfully created.' }
        format.json { render json: @spieler, status: :created, location: @spieler }
      else
        format.html { render action: "new" }
        format.json { render json: @spieler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spielers/1
  # PUT /spielers/1.json
  def update
    @spieler = Spieler.find(params[:id])

    respond_to do |format|
      if @spieler.update_attributes(params[:spieler])
        format.html { redirect_to @spieler, notice: 'Spieler was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spieler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spielers/1
  # DELETE /spielers/1.json
  def destroy
    @spieler = Spieler.find(params[:id])
    @spieler.destroy

    respond_to do |format|
      format.html { redirect_to spielers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/spielers_helper.rb
module SpielersHelper
end

app/views/spielers/_form.html.erb
<%= form_for(@spieler) do |f| %>
  <% if @spieler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spieler.errors.count, "error") %> prohibited this spieler from being saved:</h2>

      <ul>
      <% @spieler.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spielerName %><br />
    <%= f.text_field :spielerName %>
  </div>
  <div class="field">
    <%= f.label :teamID %><br />
    <%= f.number_field :teamID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spielers/edit.html.erb
<h1>Editing spieler</h1>

<%= render 'form' %>

<%= link_to 'Show', @spieler %> |
<%= link_to 'Back', spielers_path %>

app/views/spielers/index.html.erb
<h1>Listing spielers</h1>

<table>
  <tr>
    <th>Spielername</th>
    <th>Teamid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spielers.each do |spieler| %>
  <tr>
    <td><%= spieler.spielerName %></td>
    <td><%= spieler.teamID %></td>
    <td><%= link_to 'Show', spieler %></td>
    <td><%= link_to 'Edit', edit_spieler_path(spieler) %></td>
    <td><%= link_to 'Destroy', spieler, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spieler', new_spieler_path %>

app/views/spielers/new.html.erb
<h1>New spieler</h1>

<%= render 'form' %>

<%= link_to 'Back', spielers_path %>

app/views/spielers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spielername:</b>
  <%= @spieler.spielerName %>
</p>

<p>
  <b>Teamid:</b>
  <%= @spieler.teamID %>
</p>


<%= link_to 'Edit', edit_spieler_path(@spieler) %> |
<%= link_to 'Back', spielers_path %>