config/routes.rb
RailsinstallerDemo::Application.routes.draw do
  resources :tickers

  resources :games

  resources :spielers

  resources :teams

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  # GET /tickers
  # GET /tickers.json
  def index
    @tickers = Ticker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickers }
    end
  end

  # GET /tickers/1
  # GET /tickers/1.json
  def show
    @ticker = Ticker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticker }
    end
  end

  # GET /tickers/new
  # GET /tickers/new.json
  def new
    @ticker = Ticker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticker }
    end
  end

  # GET /tickers/1/edit
  def edit
    @ticker = Ticker.find(params[:id])
  end

  # POST /tickers
  # POST /tickers.json
  def create
    @ticker = Ticker.new(params[:ticker])

    respond_to do |format|
      if @ticker.save
        format.html { redirect_to @ticker, notice: 'Ticker was successfully created.' }
        format.json { render json: @ticker, status: :created, location: @ticker }
      else
        format.html { render action: "new" }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickers/1
  # PUT /tickers/1.json
  def update
    @ticker = Ticker.find(params[:id])

    respond_to do |format|
      if @ticker.update_attributes(params[:ticker])
        format.html { redirect_to @ticker, notice: 'Ticker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickers/1
  # DELETE /tickers/1.json
  def destroy
    @ticker = Ticker.find(params[:id])
    @ticker.destroy

    respond_to do |format|
      format.html { redirect_to tickers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/views/tickers/_form.html.erb
<%= form_for(@ticker) do |f| %>
  <% if @ticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticker.errors.count, "error") %> prohibited this ticker from being saved:</h2>

      <ul>
      <% @ticker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aktion_ID %><br />
    <%= f.number_field :aktion_ID %>
  </div>
  <div class="field">
    <%= f.label :spieler_ID %><br />
    <%= f.number_field :spieler_ID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickers/edit.html.erb
<h1>Editing ticker</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticker %> |
<%= link_to 'Back', tickers_path %>

app/views/tickers/index.html.erb
<h1>Listing tickers</h1>

<table>
  <tr>
    <th>Aktion id</th>
    <th>Spieler id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickers.each do |ticker| %>
  <tr>
    <td><%= ticker.aktion_ID %></td>
    <td><%= ticker.spieler_ID %></td>
    <td><%= link_to 'Show', ticker %></td>
    <td><%= link_to 'Edit', edit_ticker_path(ticker) %></td>
    <td><%= link_to 'Destroy', ticker, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticker', new_ticker_path %>

app/views/tickers/new.html.erb
<h1>New ticker</h1>

<%= render 'form' %>

<%= link_to 'Back', tickers_path %>

app/views/tickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Aktion id:</b>
  <%= @ticker.aktion_ID %>
</p>

<p>
  <b>Spieler id:</b>
  <%= @ticker.spieler_ID %>
</p>


<%= link_to 'Edit', edit_ticker_path(@ticker) %> |
<%= link_to 'Back', tickers_path %>